from models import ResultTemplate

a: ResultTemplate = {
    "label": "Machine Learning and Artificial Intelligence Innovations",
    "positions": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
    ],
    "relevancy": 1.0000000000000002,
    "children": [
        {
            "label": "Machine Learning for Security and Risk Management",
            "positions": [1, 10, 21, 22, 23, 28, 40],
            "relevancy": 18,
            "children": [
                {
                    "label": "Network Security and Risk Management Technologies",
                    "positions": [1, 10, 22],
                    "relevancy": 37,
                    "children": [],
                },
                {
                    "label": "Data Analytics for Asset Forecasting",
                    "positions": [21],
                    "relevancy": 27,
                    "children": [],
                },
                {
                    "label": "Machine Learning Security and Robustness Techniques",
                    "positions": [23, 28, 40],
                    "relevancy": 36,
                    "children": [],
                },
            ],
        },
        {
            "label": "Distributed Machine Learning Methods and Systems",
            "positions": [2, 13, 16, 20, 25, 29, 30, 37],
            "relevancy": 18,
            "children": [
                {
                    "label": "Distributed Machine Learning and Model Training",
                    "positions": [2, 13, 30],
                    "relevancy": 34,
                    "children": [],
                },
                {
                    "label": "Adaptive Machine Learning Methods",
                    "positions": [16, 29],
                    "relevancy": 31,
                    "children": [],
                },
                {
                    "label": "Distributed Machine Learning Optimization Techniques",
                    "positions": [20, 25, 37],
                    "relevancy": 35,
                    "children": [],
                },
            ],
        },
        {
            "label": "Machine Learning Dataset Transformation and Improvement",
            "positions": [3, 4, 8, 12],
            "relevancy": 17,
            "children": [],
        },
        {
            "label": "Machine Learning Systems and Applications",
            "positions": [
                5,
                6,
                7,
                11,
                14,
                17,
                18,
                19,
                24,
                26,
                27,
                32,
                33,
                35,
                36,
                38,
                39,
            ],
            "relevancy": 20,
            "children": [
                {
                    "label": "Machine Learning Systems and Techniques",
                    "positions": [5, 6, 14, 17, 19, 26, 32, 38, 39],
                    "relevancy": 29,
                    "children": [
                        {
                            "label": "Graph-Based Machine Learning Systems",
                            "positions": [5],
                            "relevancy": 31,
                            "children": [],
                        },
                        {
                            "label": "Machine Learning Systems and Techniques",
                            "positions": [6, 14, 19, 26, 32, 38, 39],
                            "relevancy": 42,
                            "children": [
                                {
                                    "label": "Autonomous Machine Learning Systems",
                                    "positions": [6],
                                    "relevancy": 30,
                                    "children": [],
                                },
                                {
                                    "label": "Machine Learning Model Training and Configuration",
                                    "positions": [14, 19],
                                    "relevancy": 33,
                                    "children": [],
                                },
                                {
                                    "label": "Machine Learning for Edge and Control Systems",
                                    "positions": [26, 32, 38, 39],
                                    "relevancy": 37,
                                    "children": [],
                                },
                            ],
                        },
                        {
                            "label": "Quantum Machine Learning Optimization",
                            "positions": [17],
                            "relevancy": 27,
                            "children": [],
                        },
                    ],
                },
                {
                    "label": "Ensemble Machine Learning Model Improvement",
                    "positions": [7],
                    "relevancy": 20,
                    "children": [],
                },
                {
                    "label": "Machine Learning Solutions and Applications",
                    "positions": [11, 18, 27, 35],
                    "relevancy": 27,
                    "children": [],
                },
                {
                    "label": "Health Monitoring and Personalized Treatment Systems",
                    "positions": [24, 33, 36],
                    "relevancy": 24,
                    "children": [],
                },
            ],
        },
        {
            "label": "Value Chain Network Optimization Technology",
            "positions": [9],
            "relevancy": 11,
            "children": [],
        },
        {
            "label": "Machine Learning and AI Enhancements",
            "positions": [15, 31, 34],
            "relevancy": 16,
            "children": [],
        },
    ],
}
