a = [
    {
        "position": 1,
        "title": "MULTI-STOREY WAGON",
        "snippet": "The closest to the proposed utility model in technical essence is a railway vehicle designed for the simultaneous transportation of automobile vehicles and passengers, comprising two floors, one equipped with seats and berths for passengers, the other is designed for automobile vehicles with a …",
        "patent_link": "https://patents.google.com/patent/RU64574U1/en",
        "thumbnail": None,
        "abstract": "The utility model relates to railway transport, namely to multi-storey railway wagons. A wagon for freight and / or passenger traffic contains at least two floors and at least four wheelsets designed to be mounted on two tracks of one railway. The cargo floors are equipped with locks for attaching wheeled vehicles to the tires of the wheels. Passenger floors are equipped with sleeping and / or seating. The width of the car at the level of the first floor is less than the width of the car at the level of subsequent floors. The implementation of the wagon of this design provides an increase in the usable area and volume of the wagon by the required number of times, by increasing the number of floors of the wagon, expanding the functional and operational capabilities of the device, by ensuring the transportation of passengers and various bulky goods in one train, and also provides increased stability of wagons , by increasing their width. 3 s.p. f-ly, 3 ill.",
        "title_full": "MULTI-STOREY WAGON",
    },
    {
        "position": 2,
        "title": "System and method for coupling/uncoupling moving guided vehicles during …",
        "snippet": "- if a coupling/uncoupling track section has been located and the coupling/uncoupling conditions are fulfilled, then automatically performing the cou ¬ pling/uncoupling of the guided vehicle units Al and A2 when the guided vehicle units Al and A2 enter said coupling/uncoupling track section (31, 32) …",
        "patent_link": "https://patents.google.com/patent/EP3250437A1/en",
        "thumbnail": None,
        "abstract": "The present invention concerns a system and a method for coupling/uncoupling two guided vehicle units while said guided vehicle units are operated and moving on a track according to a predefined itinerary, the method comprising: - receiving a command for coupling/uncoupling the guided vehicles units; - checking coupling/uncoupling conditions; - locating a coupling/uncoupling track section on the itinerary of the guided vehicle units, wherein the coupling/uncoupling track section is a track section fulfilling criteria defined for ensuring safe coupling/uncoupling operation; - if a coupling/uncoupling track section has been located and the coupling/uncoupling conditions are fulfilled, then automatically performing the coupling/uncoupling of the guided vehicle units when the guided vehicle units enter said coupling/uncoupling track section, otherwise moving the coupled/uncoupled guided vehicles units according to said itinerary until a coupling/uncoupling track section is located or a station is reached.",
        "title_full": "System and method for coupling/uncoupling moving guided vehicles during operation",
    },
    {
        "position": 3,
        "title": "Automobile frame rear structure and car",
        "snippet": "3. The automobile frame rear structure according to claim 2, characterized in that, the second connecting plate (33a) and the fourth connecting plate (33b) are the two sides of the rear beam (23). Protruding extensions. 4. The automobile frame rear structure according to claim 1, characterized in …",
        "patent_link": "https://patents.google.com/patent/CN205365745U/en",
        "thumbnail": None,
        "abstract": "A vehicle frame rear structure, comprising a first longitudinal beam and a second longitudinal beam extending along the length direction of the vehicle body, the vehicle frame rear structure also includes a first cross beam, a second cross beam, a rear cross beam, a first connecting structure and Second connection structure. The first crossbeam, the second crossbeam and the rear crossbeam are sequentially arranged at intervals between the first longitudinal beam and the second longitudinal beam along the direction to the rear of the vehicle body. The first connecting structure is arranged on the outer side of the first longitudinal beam away from the second longitudinal beam, and the first connecting structure and part of the first longitudinal beam form a quadrilateral structure. The second connection structure is arranged on the outer side of the second longitudinal beam away from the first longitudinal beam, and the second connection structure and part of the second longitudinal beam form a quadrilateral structure. The rear structure of the car frame effectively improves the local mode of the rear of the car, solves some NVH problems of the car body, and improves the safety of the car during the collision process. The utility model also relates to an automobile.",
        "title_full": "Automobile frame rear structure and car",
    },
    {
        "position": 4,
        "title": "Motor train body, motor train and motor train unit",
        "snippet": "3. The motor car body of claim 2, wherein each of the first anti-creep energy absorber has a trigger force value of 700kN to 900kN; and the triggering force value of each second anti-creeping energy absorbing device is 200kN to 600kN. 4. The motor car body of claim 1, wherein the anti-creep energy …",
        "patent_link": "https://patents.google.com/patent/CN117755349A/en",
        "thumbnail": None,
        "abstract": "The embodiment of the application provides a motor car body, a motor car and a motor train unit, wherein the motor car body comprises a chassis, a cab, a coupler energy absorbing device and an anti-creeping energy absorbing device, the cab is arranged on the upper part of the front end of the chassis, the coupler energy absorbing device is arranged on the front end of the chassis, and the anti-creeping energy absorbing device is divided into a first anti-creeping energy absorbing device and a second anti-creeping energy absorbing device; the first anti-creeping energy absorbing device is arranged at the front end part of the underframe, and the second anti-creeping energy absorbing device is at least partially arranged at the front end part of the cab; the triggering force value of the second anti-creeping energy-absorbing device is smaller than that of the first anti-creeping energy-absorbing device. According to the motor car body, the first anti-creeping energy absorbing device and the second anti-creeping energy absorbing device with different trigger force values are arranged on the underframe and/or the cab, so that the overall energy absorbing capacity value of the anti-creeping energy absorbing device arranged on the head of the motor car body is larger, the longitudinal load born by the head of the motor car body is more balanced, and the head of the motor car body can bear the longitudinal load during collision at a higher speed.",
        "title_full": "Motor train body, motor train and motor train unit",
    },
    {
        "position": 5,
        "title": "Passenger rail vehicle",
        "snippet": "Vehicle according to claim 4, wherein the lower level (20) of the front part (18) of the intermediate section (6) has an electronic equipment area (23). Vehicle according to claim 5, wherein the electronic equipment area (23) comprises batteries. Vehicle according to any of claims 3 to 6, wherein …",
        "patent_link": "https://patents.google.com/patent/EP4596365A1/en",
        "thumbnail": None,
        "abstract": "Passenger rail vehicle comprising a front section, a rear section and an intermediate section (6), the front section having a first passenger area with seats and a first boarding area, and the rear section having a second passenger area with seats and a second boarding area, each boarding area having at least one door, the intermediate section (6) has a lower level (13) and an upper level (14), the upper level (14) is arranged in a vertical direction above the lower level (13), the upper level (14) has seats (8) and the lower level (13) has a storage area (15), the lower level (13) has a first height (h1) not exceeding 1,85 metres, and the upper level (14) has a second height (h2) not exceeding 2,15 metres.",
        "title_full": "Passenger rail vehicle",
    },
    {
        "position": 6,
        "title": "Improvements in Railway and Road Passenger Vehicles.",
        "snippet": "14,584. International F-A-Y-E Tramcar Co., and Tanner, A. J. June 21. Tramcars; doors; footboards, steps, etc.; ingress and egress of passengers, controlling.-The bulkhead 3 of fare-prepayment cars is arranged to extend inwards towards the interior of the vehicle. The platform space can thus be …",
        "patent_link": "https://patents.google.com/patent/GB191214584A/en",
        "thumbnail": None,
        "abstract": "14,584. International F-A-Y-E Tramcar Co., and Tanner, A. J. June 21. Tramcars; doors; footboards, steps, etc.; ingress and egress of passengers, controlling.-The bulkhead 3 of fare-prepayment cars is arranged to extend inwards towards the interior of the vehicle. The platform space can thus be reduced and waste space avoided. The usual doors 3<1> adapted to slide into the bulkhead sections may be provided. The bulkhead and doors may be curved instead of plane as shown. The lower steps of the stairway are disposed adjacent to the offside bulkhead and opposite the exit side of the platform step 6. The floor 9 of the interior is returned outwards so that the stairway rises from it and the conductor's position C is elevated by it. Fig. 2 shows an arrangement more particularly for omnibuses, in which the front bulkhead 3<a> is shaped to correspond to that at the rear. Fig. 4 shows the arrangement for a reversible car having a central platform with detachable guide rails 5. Specifications 1252/12 and 2541/12 are referred to.",
        "title_full": "Improvements in Railway and Road Passenger Vehicles.",
    },
    {
        "position": 7,
        "title": "Improvements in Electric Railway and Tramway Vehicles.",
        "snippet": "13,176. Gibbs, G., and Pearson, H. Oct. 2, A.D. 1902, [date applied for under Patents Act, A.D. 1901]. Electric railways and tramways; electric locomotives and motor vehicles. - Relates to the arrangement of doors to facilitate the loading and unloading of cars, and to protect the controller …",
        "patent_link": "https://patents.google.com/patent/GB190313176A/en",
        "thumbnail": None,
        "abstract": "13,176. Gibbs, G., and Pearson, H. Oct. 2, A.D. 1902, [date applied for under Patents Act, A.D. 1901]. Electric railways and tramways; electric locomotives and motor vehicles. - Relates to the arrangement of doors to facilitate the loading and unloading of cars, and to protect the controller apparatus, or form a compartment for the motorman. Fig. 1 shows the general arrangement for one end of the car. The door 6 can take up the three positions shown. The buffer end of the car appears at 2, 1 being the flooring of the car platform. The sliding side door 15 can be actuated by the motorman by means of the handle 16, which works the levers shown. Fig. 2 shows two cars joined up to form a train, which have unobstructed platform vestibules besides the side doors.",
        "title_full": "Improvements in Electric Railway and Tramway Vehicles.",
    },
    {
        "position": 8,
        "title": "Hidden seat protection mechanism for motor car cab",
        "snippet": "2. The hidden seat protection mechanism for the cab of the motor vehicle as claimed in claim 1, wherein: the other end of the safety airbag storage box (9) is fixed with the base (5) through a second support plate (4). 3. The hidden seat protection mechanism for the cab of the motor vehicle as …",
        "patent_link": "https://patents.google.com/patent/CN210502692U/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/24/e0/e0/2ecd0b5a536e59/HDA0002091999020000011.png",
        "abstract": "The utility model discloses a motor car cab is with hiding seat protection machanism, including the cab main part, cab main part internally mounted has safety seat, install the protection back on the safety seat, and protect back upper end surface mounting and have safe headrest, safety seat's both ends are fixed with the baffle handle, and baffle handle surface is provided with the safety belt locked groove, the safety seat bottom is provided with the cushion main part, and cushion main part bottom installs the supporting pad, the air bag bin is installed to the supporting pad lower extreme, the one end of air bag bin is fixed mutually with the protection back through first backup pad. The utility model discloses an install the protection formula design to motor car cab with the seat, be provided with hidden gasbag protection mechanism, can open the gasbag when dangerous and carry out safety protection to the driver, be provided with the safety belt locked groove simultaneously, be convenient for fix the safety belt.",
        "title_full": "Hidden seat protection mechanism for motor car cab",
    },
    {
        "position": 9,
        "title": "Railway-vehicle for combined rail-road transport and train unit incorporating …",
        "snippet": "2. A vehicle according to claim The method of claim 1, characterized in that the thickness of the movable platform (4) is in the order of 50 mm. 3. A vehicle according to claim 3. A method according to claim 1, characterized in that the usable length (L) of railway vehicle platforms for combined …",
        "patent_link": "https://patents.google.com/patent/PL184568B1/en",
        "thumbnail": None,
        "abstract": "1. A railway vehicle for combined rail-road transport, comprising a stand with a moving platform and bogies arranged on both sides of the platform, stubs of the stand which are placed in front of the first axle of the wagon bogies in relation to the center of the stand, which includes a unit transferring the load between the first axle and the second axle of the bogie, characterized in that it contains an element (12) for centering the frame (2) of the railway vehicle (1) in a given dimension pattern, with the element (12) mounted around the pin (6) of the frame (2) railway vehicle (1), whereby the self-adjusting pin is controlled laterally by the control element (13). FIG 2 PL PL PL PL PL PL PL",
        "title_full": "Railway-vehicle for combined rail-road transport and train unit incorporating such vehicle",
    },
    {
        "position": 10,
        "title": "Autorail and a method for rail-road transport",
        "snippet": "Patent claims 1. A rail-road vehicle with a carrying platform, a car chassis with a wishbone-air suspension and a railway chassis, characterized by the fact that it has a railway chassis permanently connected to the carrying platform (1) and operating alternately with the car chassis, equipped …",
        "patent_link": "https://patents.google.com/patent/PL220512B1/en",
        "thumbnail": None,
        "abstract": "",
        "title_full": "Autorail and a method for rail-road transport",
    },
    {
        "position": 11,
        "title": "Railway-car",
        "snippet": "hen the car is a double-decked car, or has seats L upon the roof a arranged as shown either in Figs. 4 or 5, the roof is suitably railed or inclosed, as shown at M, and a spiral or other suitably-constructed stairway, m, is erected at the closed side or end b of platform 13, and leads to the roof a …",
        "patent_link": "https://patents.google.com/patent/US378428A/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/37/9f/c8/8f772655a5c4aa/US378428-drawings-page-1.png",
        "abstract": "",
        "title_full": "Railway-car",
    },
    {
        "position": 12,
        "title": "Increased power emergency braking system for trains",
        "snippet": "Railway braking system having rubber tyre wheels 2, 3 which may be lowered into contact with the rail 4 during emergency braking for enlarging the contact patch and thus increasing grip to improve brake force of a rail vehicle 1 (e.g. locomotive, train carriage, wagon, rolling stock). The rubber …",
        "patent_link": "https://patents.google.com/patent/GB2611794A/en",
        "thumbnail": None,
        "abstract": "Railway braking system having rubber tyre wheels 2, 3 which may be lowered into contact with the rail 4 during emergency braking for enlarging the contact patch and thus increasing grip to improve brake force of a rail vehicle 1 (e.g. locomotive, train carriage, wagon, rolling stock). The rubber tyre wheels 2, 3 are normally stowed retracted and away from contact with the rail during normal operation (fig 2).",
        "title_full": "Increased power emergency braking system for trains",
    },
    {
        "position": 13,
        "title": "A vehicle transporting large-capacity containers",
        "snippet": "Vehicle according to claim 1 or 2, characterized in that there is space for a manipulator (11) with containers (8) between the self-supporting frame (2) and the platform (7). -3CZ 32691 UI A vehicle according to any one of claims 1 to 3, characterized in that the couplings (6) with an electrical …",
        "patent_link": "https://patents.google.com/patent/CZ32691U1/en",
        "thumbnail": None,
        "abstract": "",
        "title_full": "A vehicle transporting large-capacity containers",
    },
    {
        "position": 14,
        "title": "Patent JPS6312038Y2",
        "snippet": "In a railway vehicle consisting of a car carrier that has been modified to meet the vehicle limits, the end of the car carrier with a high-speed bogie is reinforced with side beams and horizontal beams, and an adsorption magnet is attached to the floor reinforced with the horizontal beams.",
        "patent_link": "https://patents.google.com/patent/JPS6312038Y2/en",
        "thumbnail": None,
        "abstract": "",
        "title_full": "",
    },
    {
        "position": 15,
        "title": "A kind of train safety tracking protection method and device based on relative …",
        "snippet": "Step 2, using the communication method between vehicles, the rear vehicle obtains the safety space-time trajectory information of the preceding vehicle; Step 3, the rear vehicle combines the safety space-time trajectory information of the front vehicle and the rear vehicle, establishes a safety …",
        "patent_link": "https://patents.google.com/patent/CN111845862B/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/cb/3c/f7/2d6d1377c0c456/HDA0002583530250000011.png",
        "abstract": "The embodiment of the present invention provides a relative speed-based train safety tracking protection method and device, the method includes: step 1, tracking the running preceding vehicle and the rear vehicle using an electronic map and autonomous speed measurement and positioning information combined with train performance to obtain respectively The safety space-time trajectory information of the current train during the parking process; step 2, the rear vehicle obtains the safety space-time trajectory information of the preceding vehicle by using the inter-vehicle communication method; step 3, the rear vehicle combines the The safety space-time trajectory information of the preceding vehicle and the rear vehicle is established according to the constraint that the position of the rear vehicle cannot exceed the position of the preceding vehicle at any time, and a safety condition is established to solve the emergency braking trigger EBI speed of the rear vehicle; Step 4, all The rear vehicle compares whether the current measured speed v  2  (t  0  ) of the rear vehicle exceeds the EBI speed E  2  (t  0  ) of the rear vehicle; if v  2  (t  0  )>E  2  (t  0  ), then An emergency braking command is output to decelerate the rear vehicle to a stop.",
        "title_full": "A kind of train safety tracking protection method and device based on relative speed",
    },
    {
        "position": 16,
        "title": "System and method for controlling a vehicle system to achieve different …",
        "snippet": "A system (e.g., a control system) includes a sensor configured to monitor an operating condition of a vehicle system during movement of the vehicle system along a route. The system also includes a controller configured to designate one or more operational settings for the vehicle system as a …",
        "patent_link": "https://patents.google.com/patent/AU2020286260B2/en",
        "thumbnail": None,
        "abstract": "A system (e.g., a control system) includes a sensor configured to monitor an operating \ncondition of a vehicle system during movement of the vehicle system along a route. The system \nalso includes a controller configured to designate one or more operational settings for the vehicle \nsystem as a function of time and/or distance along the route. The controller is configured to \noperate in a first operating mode responsive to the operating condition of the vehicle system \nbeing at least one of at or above a designated threshold, and in a second operating mode \nresponsive to the operating condition of the vehicle system being below the designated threshold.  \nThe controller designates operational settings to drive the vehicle system toward achievement of \na first objective when in the first operating mode and toward achievement of a different, second \nobjective when in the second operating mode.",
        "title_full": "System and method for controlling a vehicle system to achieve different objectives during a trip",
    },
    {
        "position": 17,
        "title": "Vehicle systems configured to interact with remotely located smart systems",
        "snippet": "6 . The vehicle of claim 2 , wherein the device is a garage door controllable via the smart home system. 7 . The vehicle of claim 2 , wherein the device is a refrigerator controllable via the smart home system. 8 . The vehicle of claim 1 , wherein the information included in the second message indicates …",
        "patent_link": "https://patents.google.com/patent/US20240370627A1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/1f/73/29/4eff012ca606a4/US20240370627A1-20241107-D00000.png",
        "abstract": "Vehicle systems configured to interact with remotely located smart systems are disclosed. An example vehicle includes memory, machine-readable instructions, and one or more processors. The one or more processors are configured to execute the machine-readable instructions to send, from the vehicle to a smart system located remotely relative to the vehicle, a first message configured to cause the smart system to adjust one or more functions of a device controllable via the smart system. The one or more processors are further configured to execute the machine-readable instructions to receive, at the vehicle from the smart system, a second message including information associated with the smart system or the device.",
        "title_full": "Vehicle systems configured to interact with remotely located smart systems",
    },
    {
        "position": 18,
        "title": "System and method of providing recommendations to users of vehicles",
        "snippet": "What is claimed is: 1. A system for controlling a first-vehicle in an autonomous driving mode, the system comprising one or more processors configured to: receive information including data generated by a sensor remote from the vehicle; determine one or more types of maneuvers for the vehicle based …",
        "patent_link": "https://patents.google.com/patent/US12197215B1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/11/58/84/bf6e94c19528d4/US12197215-20250114-D00000.png",
        "abstract": "A system and method are arranged to provide recommendations to a user of a vehicle. In one aspect, the vehicle navigates in an autonomous mode and the sensors provide information that is based on the location of the vehicle and output from sensors directed to the environment surrounding the vehicle. In further aspects, both current and previous sensor data is used to make the recommendations, as well as data based on the sensors of other vehicles.",
        "title_full": "System and method of providing recommendations to users of vehicles",
    },
    {
        "position": 19,
        "title": "Vehicle middleware",
        "snippet": "5 . The vehicle of claim 4 , wherein the second wireless communication protocol is a WiFi communication protocol. 6 . The vehicle of claim 1 , wherein the external computational device is a mobile device. 7 . The vehicle of claim 6 , wherein the mobile device is a smartphone. 8 . The vehicle of claim 1 ,",
        "patent_link": "https://patents.google.com/patent/US20250174116A1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/a2/26/0d/52abc17797a6d8/US20250174116A1-20250529-D00000.png",
        "abstract": "The present disclosure describes a vehicle including a first wireless interface configured to communicate with an external computational device using a first wireless communication protocol, and a second wireless interface configured to communicate with the external computational device using a second wireless communication protocol that is different from the first wireless communication protocol. The vehicle further includes a network controller having a network selector configured to select either the first wireless communication protocol or the second wireless communication protocol for communication with the external computational device. The selection is based on one or more signals received at the network controller from the external computational device. The network selector selects the first wireless communication protocol to communicate with the external computational device at a first time, and selects the second wireless communication protocol to communicate with the external computational device at a second time different from the first time.",
        "title_full": "Vehicle middleware",
    },
    {
        "position": 20,
        "title": "Use of chimeric antigen receptor engineered T cells to treat cancer",
        "snippet": "A pharmaceutical composition for treating a hematological malignancy in a human patient comprising a human T cell comprising a nucleic acid sequence encoding a chimeric antigen receptor (CAR), the composition comprising: The CAR comprises a CD19 antigen-binding domain encoded by a nucleic acid …",
        "patent_link": "https://patents.google.com/patent/JP7426361B2/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/04/2c/26/1181121e3da55b/0007426361000009.png",
        "abstract": "",
        "title_full": "Use of chimeric antigen receptor engineered T cells to treat cancer",
    },
    {
        "position": 21,
        "title": "Systems and methods for safe and reliable autonomous vehicles",
        "snippet": "1 . A vehicle controller comprising: a behavior planner; a lane planner; a route planner; and a behavior selector, wherein the behavior planner, lane planner, and route planner are hierarchically interconnected and execute using one or more hardware-based deep learning accelerators.",
        "patent_link": "https://patents.google.com/patent/US20230176577A1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/aa/b9/b2/6de093c518ed95/US20230176577A1-20230608-D00000.png",
        "abstract": "Autonomous driving is one of the world's most challenging computational problems. Very large amounts of data from cameras, RADARs, LIDARs, and HD-Maps must be processed to generate commands to control the car safely and comfortably in real-time. This challenging task requires a dedicated supercomputer that is energy-efficient and low-power, complex high-performance software, and breakthroughs in deep learning AI algorithms. To meet this task, the present technology provides advanced systems and methods that facilitate autonomous driving functionality, including a platform for autonomous driving Levels 3, 4, and/or 5. In preferred embodiments, the technology provides an end-to-end platform with a flexible architecture, including an architecture for autonomous vehicles that leverages computer vision and known ADAS techniques, providing diversity and redundancy, and meeting functional safety standards. The technology provides for a faster, more reliable, safer, energy-efficient and space-efficient System-on-a-Chip, which may be integrated into a flexible, expandable platform that enables a wide-range of autonomous vehicles, including cars, taxis, trucks, and buses, as well as watercraft and aircraft.",
        "title_full": "Systems and methods for safe and reliable autonomous vehicles",
    },
    {
        "position": 22,
        "title": "Autonomous Vehicle Systems",
        "snippet": "providing the input to the behavioral model and comparing an output of the behavioral model to the corresponding output of the at least one machine learning model. at least one interface for receiving a signal identifying a second vehicle in proximity to the first vehicle; A processing circuit,",
        "patent_link": "https://patents.google.com/patent/JP7707487B2/en",
        "thumbnail": None,
        "abstract": "",
        "title_full": "Autonomous Vehicle Systems",
    },
    {
        "position": 23,
        "title": "… and vehicles for capturing emotion of a human driver and customizing vehicle …",
        "snippet": "Methods and systems for determining an emotion of a human driver of a vehicle and using the emotion for generating a vehicle response, is provided. One example method includes processing captured voice data from the human driver over a period of time while the human driver operates the vehicle.",
        "patent_link": "https://patents.google.com/patent/US20240105176A1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/0e/59/24/43327fb990c7f8/US20240105176A1-20240328-D00000.png",
        "abstract": "Methods and systems for determining an emotion of a human driver of a vehicle and using the emotion for generating a vehicle response, is provided. One example method includes processing captured voice data from the human driver over a period of time while the human driver operates the vehicle. The method includes analyzing the voice data to assist in prediction of the emotion of the human driver. The method includes generating the vehicle response. The vehicle response is selected in part based on the emotion that was predicted for the human driver.",
        "title_full": "Methods and vehicles for capturing emotion of a human driver and customizing vehicle response",
    },
    {
        "position": 24,
        "title": "Varying lidar illumination responsive to ambient light levels",
        "snippet": "Consistent with a disclosed embodiment, a vibration suppression system for a LIDAR configured for use on a vehicle may include at least one processor configured to: control at least one light source in a manner enabling light flux of light from the at least one light source to vary over scans of a …",
        "patent_link": "https://patents.google.com/patent/US20220050203A1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/b9/9c/a3/14777b6e83b9d5/US20220050203A1-20220217-D00000.png",
        "abstract": "A LIDAR system is provided. The LIDAR system may include at least one processor configured to: control at least one light deflector to deflect light from a plurality of light sources towards a region in a field of view while the at least one light deflector is in a particular instantaneous position; control the at least one light deflector such that while the at least one light deflector is at the particular instantaneous position, light reflections from the field of view are received on at least one common area along a plurality of return paths to at least one sensor; and receive from at least one of a plurality of light detectors included in the at least one sensor, signals associated with beam spots of the received light reflections, wherein each of the beam spots impinges on more than one of the plurality of light detectors.",
        "title_full": "Varying lidar illumination responsive to ambient light levels",
    },
    {
        "position": 25,
        "title": "Component and sensor for a lidar sensor system, lidar sensor system and method …",
        "snippet": "The LIDAR Sensor System and/or LIDAR Sensor Device can further include light emitting and light sensing elements that can be used for illumination purposes, like road lighting, or for data communication purposes, for example car-to-car, car-to-environment (for example drones, pedestrian, traffic …",
        "patent_link": "https://patents.google.com/patent/US20220276351A1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/f9/74/67/38b4ac9f690c04/US20220276351A1-20220901-D00000.png",
        "abstract": "The present disclosure relates to various embodiments of an optical component for a LIDAR Sensor System. The optical component includes a first photo diode implementing a LIDAR sensor pixel in a first semiconductor structure and configured to absorb received light in a first wavelength region, a second photo diode implementing a camera sensor pixel in a second semiconductor structure over the first semiconductor structure and configured to absorb received light in a second wavelength region, and an interconnect layer (e.g. arranged between the first semiconductor structure and the second semiconductor structure) including an electrically conductive structure configured to electrically contact the second photo diode. The received light of the second wavelength region has a shorter wavelength than the received light of the first wavelength region.",
        "title_full": "Component and sensor for a lidar sensor system, lidar sensor system and method for a lidar sensor system",
    },
    {
        "position": 26,
        "title": "Method and system for modifying a control unit of an autonomous car",
        "snippet": "A method for modifying a control unit of an autonomous car (30), the autonomous car (30) being equipped with basic sensors adapted for recording sensor data based on which a fusion model of objects and an environment surrounding the autonomous car (30) can be generated, wherein the sensor data …",
        "patent_link": "https://patents.google.com/patent/EP3877740B1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/20/44/e6/c99712cba28c5c/imgf0001.png",
        "abstract": "",
        "title_full": "Method and system for modifying a control unit of an autonomous car",
    },
    {
        "position": 27,
        "title": "Self-driving car and self-driving car anti-theft program",
        "snippet": "The self-driving car according to any one of claims 1 to 12, wherein the location information of the escaped suspected thief is sent to a police agency. The theft detection means includes a biometric information acquisition unit. A claim characterized in that it detects that the vehicle is in a …",
        "patent_link": "https://patents.google.com/patent/JP6882809B2/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/99/9e/38/eb5a2cf66622d4/0006882809-2.png",
        "abstract": "",
        "title_full": "Self-driving car and self-driving car anti-theft program",
    },
    {
        "position": 28,
        "title": "Automatic determination of rental car term associated with a vehicle collision …",
        "snippet": "claim 1 , wherein the automatically detecting that the mobile computing device is within the vehicle that was involved in the accident comprises: receiving, by the processor, data from a vehicle-based computing device of a first vehicle indicating that the first vehicle was involved in the accident.",
        "patent_link": "https://patents.google.com/patent/US11037107B1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/fa/98/db/343bf9bd201642/US11037107-20210615-D00000.png",
        "abstract": "One or more devices in an accident detection and recovery computing system may be configured to determine that vehicle accidents have occurred, collect and analyze accident characteristics and other related data, and providing customized accident recovery services. Mobile computing devices, alone or in combination with vehicle-based systems and external devices, may detect accidents or receive accident indication data. After determining that an accident has occurred, mobile computing devices and/or vehicle-based systems may be configured to determine accident characteristics, and then determine the damages or potential damages resulting from the accident. With an estimated assessment of damage, an accurate estimated of the amount of time to repair the damaged vehicle may be calculated, thus an automatic determination of the amount of time a user may need a rental car during the vehicle collision repair may occur.",
        "title_full": "Automatic determination of rental car term associated with a vehicle collision repair incident",
    },
    {
        "position": 29,
        "title": "Digital car keys and sharing of digital car keys using mobile devices",
        "snippet": "accessing an application on the first mobile device to select sharing of the e-key and identification of a recipient of the e-key, the recipient associated with the second mobile device, wherein the first mobile device is paired with the vehicle with an administrator e-key before sending the …",
        "patent_link": "https://patents.google.com/patent/US11305666B2/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/70/6e/e7/512d400b59797a/US11305666-20220419-D00000.png",
        "abstract": "Methods and systems for sharing digital electronic keys (e-keys) to use a vehicle with the e-key are provided. One example method includes sending, via a first application of a first mobile device, a message to a second mobile device to initiate providing access to the vehicle via the e-key. The method includes receiving, by the first mobile device, data confirming from the second mobile device indicating receipt and creating the e-key at the second mobile device for the vehicle with a level of access that was set via the first application of the first mobile device. The data confirming receipt for the e-key is authenticated by the first mobile device. The method includes sending, by the first mobile device, verification of the e-key for use via the second mobile device. The e-key is registered with a server to enable activation of the e-key on the second mobile device. A second application of the second mobile device provides a user interface for access of the e-key for unlocking and starting the vehicle. In one example, the e-key is usable via wireless communication with the vehicle over a near field communication (NFC) connection. In one example, the first application of the first mobile device is provided with an interface to enable revocation to disable the e-key shared with a user of the second mobile device.",
        "title_full": "Digital car keys and sharing of digital car keys using mobile devices",
    },
    {
        "position": 30,
        "title": "Use of icos-based cars to enhance antitumor activity and car persistence",
        "snippet": "The present invention provides compositions and methods for treating cancer in a human. The invention includes administering a genetically modified Th17 cell to express a CAR having an antigen binding domain, a transmembrane domain, and an ICOS intracellular signaling domain.",
        "patent_link": "https://patents.google.com/patent/US20240301024A1/en",
        "thumbnail": "https://patentimages.storage.googleapis.com/ee/86/af/e1de85bc8b3068/US20240301024A1-20240912-D00001.png",
        "abstract": "The present invention provides compositions and methods for treating cancer in a human. The invention includes administering a genetically modified Th17 cell to express a CAR having an antigen binding domain, a transmembrane domain, and an ICOS intracellular signaling domain.",
        "title_full": "Use of icos-based cars to enhance antitumor activity and car persistence",
    },
]
